# .github/workflows/dummy-check.yml
name: Status Check

on:
  pull_request:
    branches:
      - dev

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Pass status check
        run: echo "Status check passed ✅"
